### PR TITLE
Upgrade pip-tools, upgrade deps, add Python 3.5 and 2.6

### PR DESCRIPTION
**Pull request by paulkernfeld**
Hi guys!

### CODE REVIEW

**Comment by alexroussos** [comment]
Caio Paolo!

**Comment by khwilson** [comment]
Thanks, Paul! Would you mind adding py35 (since that's the latest version)?

**Comment by paulkernfeld** [comment]
@khwilson good point! Done.

**Comment by khwilson** [comment]
Excellent! Merged :+1:

**Comment by paulkernfeld** [comment]
Thanks @khwilson !

**Pull request merged**
